import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Card from '../components/Card'
import useTrackLocation from '../hooks/use-track-location'
import { fetchCoffeeStore } from '../lib/coffee-stores'
import { useEffect, useState } from 'react'

export async function getStaticProps(context) {

  const coffeeStores = await fetchCoffeeStore();

  return {
    props: {
      coffeeStores
    }, // will be passed to the page component as props
  }
}


export default function Home(props) {

const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } = useTrackLocation();
  console.log({ latLong })

const [coffeeStores, setCoffeeStores] = useState('');

  useEffect(async () => {
    if (latLong) {
      try {
        const fetchedCoffeeStores = await fetchCoffeeStore(latLong, 10);
        console.log({ fetchedCoffeeStores });
        setCoffeeStores(fetchedCoffeeStores);
        // set coffee stores
      } catch(error) {
        // set error
        console.log({ error })
      }
    }

  }, [latLong])

  const handleOnBannerButtonClick = () => {
    console.log('button clicked')
    handleTrackLocation()
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby."}
          handleOnClick={handleOnBannerButtonClick}
        />

        <div>
          {locationErrorMsg ? `Something went wrong: ${locationErrorMsg}` : ''}
        </div>
        <div className={styles.heroImage}>
          <Image  src="/static/hero-image.png" width={700} height={400}/>
        </div>


        {coffeeStores.length > 0 && (
        <div className={styles.sectionWrapper}>
        <h2 className={styles.heading2}>Stores Near Me</h2> 
        <div className={styles.cardLayout}>
          {coffeeStores.map((coffeeStore) => {
            return ( 
              <Card
                key={coffeeStore.id}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                href={`/coffee-store/${coffeeStore.fsq_id}`}
                className={styles.card}
              />
            );
          })}
        </div>
        </div>
        )}

        {props.coffeeStores.length > 0 ? <h2 className={styles.heading2}>Toronto Stores</h2> : <div></div> }
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
            return ( 
              <Card
                key={coffeeStore.id}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                href={`/coffee-store/${coffeeStore.fsq_id}`}
                className={styles.card}
              />
            );
          })}
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
