import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Card from '../components/Card'
import useTrackLocation from '../hooks/use-track-location'

import coffeeStoresSeed from '../data/coffee-stores.json';

export async function getStaticProps(context) {

  const data = coffeeStoresSeed;
  return {
    props: {
      coffeeStores: coffeeStoresSeed
    }, // will be passed to the page component as props
  }
}


export default function Home(props) {

const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } = useTrackLocation();


  console.log(props);
  console.log({ latLong })
  console.log({ locationErrorMsg })

  const handleOnBannerButtonClick = () => {
    console.log('button clicked')
    handleTrackLocation()
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby."}
          handleOnClick={handleOnBannerButtonClick}
        />

        <div>
          {locationErrorMsg ? `Something went wrong: ${locationErrorMsg}` : ''}
        </div>
        <div className={styles.heroImage}>
          <Image  src="/static/hero-image.png" width={700} height={400}/>
        </div>
        {props.coffeeStores.length > 0 ? <h2 className={styles.heading2}>Toronto Stores</h2> : <div></div> }
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
            return ( 
              <Card
                key={coffeeStore.id}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl}
                href={`/coffee-store/${coffeeStore.id}`}
                className={styles.card}
              />
            );
          })}
          
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
